project_name: appclacks

builds:
  - binary: appclacks
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    goos:
      - windows
      - darwin
      - linux
      - openbsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
  - tap:
      owner: appclacks
      name: homebrew-tap
    name: appclacks
    folder: Formula
    homepage: https://appclacks.com
    skip_upload: auto
    test: |
      system "#{bin}/appclacks --help"
    install: |
      bin.install "appclacks"
